from sqlalchemy import ForeignKey, String, Text
from sqlalchemy import JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin


class Business(UUIDMixin, TimestampMixin, Base):
    __tablename__ = "businesses"

    user_id: Mapped[str | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), index=True)
    workspace_id: Mapped[str | None] = mapped_column(UUID(as_uuid=True), ForeignKey("workspaces.id", ondelete="SET NULL"), index=True)
    project_id: Mapped[str | None] = mapped_column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="SET NULL"), index=True)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    niche: Mapped[str] = mapped_column(String(140), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    target_audience: Mapped[str] = mapped_column(String(220), nullable=False)
    monetization_model: Mapped[str] = mapped_column(String(160), nullable=False)
    brand_tone: Mapped[str] = mapped_column(String(120), nullable=False, default="clear and trustworthy")
    headline: Mapped[str] = mapped_column(String(180), nullable=False)
    subheading: Mapped[str] = mapped_column(Text, nullable=False)
    product_pitch: Mapped[str] = mapped_column(Text, nullable=False)
    cta_text: Mapped[str] = mapped_column(String(80), nullable=False, default="Start now")
    seo_title: Mapped[str] = mapped_column(String(180), nullable=False)
    seo_description: Mapped[str] = mapped_column(String(260), nullable=False)
    raw_ai_payload: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    # Rich page content generated by AI (pain points, features, social proof, etc.)
    page_content: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)

    user = relationship("User", back_populates="businesses", foreign_keys=[user_id])
    workspace = relationship("Workspace", back_populates="businesses")
    project = relationship("Project", back_populates="businesses")
    products = relationship("Product", back_populates="business", cascade="all, delete-orphan")
    analytics_events = relationship("AnalyticsEvent", back_populates="business", cascade="all, delete-orphan")
    orders = relationship("Order", back_populates="business", cascade="all, delete-orphan")
    agent_logs = relationship("AgentLog", back_populates="business", cascade="all, delete-orphan")
    agent_tasks = relationship("AgentTask", back_populates="business", cascade="all, delete-orphan")
    experiments = relationship("Experiment", back_populates="business", cascade="all, delete-orphan")
    campaigns = relationship("MarketingCampaign", back_populates="business", cascade="all, delete-orphan")
    seo_content = relationship("SeoContent", back_populates="business", cascade="all, delete-orphan")
    support_conversations = relationship("SupportConversation", back_populates="business", cascade="all, delete-orphan")
    payment_transactions = relationship("PaymentTransaction", back_populates="business")
    usage_ledger_entries = relationship("UsageLedger", back_populates="business")
