"""Marketing-related ORM models: campaigns, SEO content, ad payloads, support chats."""
from __future__ import annotations

from sqlalchemy import Boolean, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy import JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin


class MarketingCampaign(UUIDMixin, TimestampMixin, Base):
    """An email or ad campaign tied to a business."""

    __tablename__ = "marketing_campaigns"

    business_id: Mapped[str] = mapped_column(
        UUID(as_uuid=True), ForeignKey("businesses.id", ondelete="CASCADE"), index=True
    )
    product_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("products.id", ondelete="SET NULL"), index=True
    )
    project_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id", ondelete="SET NULL"), index=True
    )
    # "email" | "seo_blog" | "social" | "google_ads" | "meta_ads"
    campaign_type: Mapped[str] = mapped_column(String(40), nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    # "draft" | "pending_approval" | "approved" | "sent" | "rejected"
    status: Mapped[str] = mapped_column(String(40), nullable=False, default="draft", index=True)
    # AI-generated content payload (subject, body, ad copy, blog post, etc.)
    content: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    # Targeting / audience config
    targeting: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    # Metrics after execution
    metrics: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    # Who approved/rejected
    approved_by: Mapped[str | None] = mapped_column(String(255))
    rejection_reason: Mapped[str | None] = mapped_column(Text)
    # Extended lifecycle and A/B test fields
    lifecycle_status: Mapped[str] = mapped_column(String(40), nullable=False, default="draft")
    scheduled_at: Mapped[str | None] = mapped_column(String(255))
    image_url: Mapped[str | None] = mapped_column(String(500))
    ab_test_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    variant_b_content: Mapped[str | None] = mapped_column(Text)

    business = relationship("Business", back_populates="campaigns")
    product = relationship("Product")


class SeoContent(UUIDMixin, TimestampMixin, Base):
    """AI-generated SEO blog post or page content."""

    __tablename__ = "seo_content"

    business_id: Mapped[str] = mapped_column(
        UUID(as_uuid=True), ForeignKey("businesses.id", ondelete="CASCADE"), index=True
    )
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    slug: Mapped[str] = mapped_column(String(300), nullable=False, index=True)
    meta_description: Mapped[str] = mapped_column(String(500), nullable=False)
    content_markdown: Mapped[str] = mapped_column(Text, nullable=False)
    keywords: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    # "draft" | "published"
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    word_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    business = relationship("Business", back_populates="seo_content")


class SupportConversation(UUIDMixin, TimestampMixin, Base):
    """Customer support chat conversation."""

    __tablename__ = "support_conversations"

    business_id: Mapped[str] = mapped_column(
        UUID(as_uuid=True), ForeignKey("businesses.id", ondelete="CASCADE"), index=True
    )
    visitor_token: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    # "open" | "resolved"
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="open")
    messages: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    # Summary generated by AI after conversation
    summary: Mapped[str | None] = mapped_column(Text)

    business = relationship("Business", back_populates="support_conversations")
