"""Marketing Engine — real AI-generated campaigns, SEO content, and ad payloads.

All content is generated by the real AI provider (Ollama/Groq/HF).
No dummy data. If AI is unavailable, raises AIProviderError.

Approval workflow:
- Email campaigns → status="pending_approval" until user approves
- Ad campaigns → status="pending_approval" always (never auto-launch)
- SEO blogs → status="draft", user publishes manually

Uses SmartAIOrchestrator for intelligent provider selection and retry strategy.
"""
from __future__ import annotations

import logging
import re
import json
from uuid import UUID

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.analytics import AnalyticsEvent
from app.models.marketing import CampaignRecipient, Contact, MarketingCampaign, SeoContent
from app.services.ai_orchestrator import generate_json_smart, generate_text_smart, ProviderChoice

logger = logging.getLogger(__name__)


REPORT_INTELLIGENCE_CONTEXT = (
    "Product intelligence from the production hardening report:\n"
    "- Strongest initial wedge: residential home services, especially HVAC, plumbing, electrical, and roofing operators under 20 employees.\n"
    "- Primary customer pain: missed leads, slow follow-up, weak local marketing, disconnected scheduling, and no booked-revenue attribution.\n"
    "- Marketing outputs should emphasize booked calls, service appointments, quote requests, review generation, and real tracked campaign events over vanity metrics.\n"
    "- Production rule: generate useful assets, but never claim sending, publishing, spend, revenue, or platform success unless a real backend/provider action confirms it.\n"
    "- If the selected business is not a home-services business, apply the same operating-system logic to that niche without pretending it belongs to home services.\n"
)


class MarketingService:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db

    # ── SEO Content ───────────────────────────────────────────────────────────

    async def generate_seo_blog(
        self,
        business_id: UUID,
        topic: str,
        target_keyword: str,
        business_context: dict,
    ) -> SeoContent:
        """Generate a full SEO blog post using real AI with smart provider selection."""
        prompt = (
            "You are an expert SEO content writer.\n"
            "Write a complete, high-quality SEO blog post.\n"
            "Return ONLY valid JSON with these keys:\n"
            "  title, slug, meta_description, content_markdown, keywords (array of strings)\n\n"
            f"Business: {business_context.get('name')}\n"
            f"Niche: {business_context.get('niche')}\n"
            f"Target audience: {business_context.get('target_audience')}\n"
            f"Topic: {topic}\n"
            f"Primary keyword: {target_keyword}\n\n"
            f"{REPORT_INTELLIGENCE_CONTEXT}\n"
            "Requirements:\n"
            "- Title: compelling, includes keyword, under 60 chars\n"
            "- Slug: URL-friendly, lowercase, hyphens\n"
            "- Meta description: 150-160 chars, includes keyword\n"
            "- Content: 800-1200 words, markdown format, H2/H3 headings, practical value\n"
            "- Keywords: 5-8 related keywords"
        )
        # Use smart orchestrator for intelligent provider selection
        data = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")
        content_md = data.get("content_markdown", "")
        word_count = len(content_md.split())

        seo = SeoContent(
            business_id=business_id,
            title=data.get("title", topic),
            slug=data.get("slug", re.sub(r"[^a-z0-9]+", "-", topic.lower())),
            meta_description=data.get("meta_description", ""),
            content_markdown=content_md,
            keywords=data.get("keywords", [target_keyword]),
            status="draft",
            word_count=word_count,
        )
        self.db.add(seo)
        await self.db.commit()
        await self.db.refresh(seo)
        logger.info("SEO blog generated  business_id=%s  title=%r", business_id, seo.title)
        return seo

    async def list_seo_content(self, business_id: UUID) -> list[SeoContent]:
        result = await self.db.execute(
            select(SeoContent)
            .where(SeoContent.business_id == business_id)
            .order_by(SeoContent.created_at.desc())
        )
        return list(result.scalars().all())

    async def publish_seo_content(self, content_id: UUID) -> SeoContent | None:
        content = await self.db.get(SeoContent, content_id)
        if not content:
            return None
        content.status = "published"
        await self.db.commit()
        return content

    # ── Email Campaigns ───────────────────────────────────────────────────────

    async def generate_email_campaign(
        self,
        business_id: UUID,
        campaign_name: str,
        goal: str,
        business_context: dict,
        product_context: dict | None = None,
        project_id: UUID | None = None,
        product_id: UUID | None = None,
        recipient_count: int = 0,
    ) -> MarketingCampaign:
        """Generate an email campaign. Requires human approval before sending."""
        product_block = ""
        if product_context:
            product_block = (
                f"Featured product: {product_context.get('name')}\n"
                f"Product description: {product_context.get('description')}\n"
                f"Product price: {product_context.get('price')} {product_context.get('currency', 'USD')}\n"
                f"Product type: {product_context.get('product_type', 'digital')}\n"
            )
        prompt = (
            "You are an expert email marketer.\n"
            "Generate a high-converting email campaign.\n"
            "Return ONLY valid JSON with these keys:\n"
            "  subject, preview_text, html_body, plain_text_body, cta_text, cta_url_placeholder\n\n"
            f"Business: {business_context.get('name')}\n"
            f"Niche: {business_context.get('niche')}\n"
            f"Brand tone: {business_context.get('brand_tone', 'professional')}\n"
            f"Target audience: {business_context.get('target_audience')}\n"
            f"{product_block}"
            f"Campaign goal: {goal}\n\n"
            f"{REPORT_INTELLIGENCE_CONTEXT}\n"
            "Requirements:\n"
            "- Subject: compelling, under 50 chars, no spam words\n"
            "- Preview text: 90-100 chars\n"
            "- HTML body: clean HTML email, mobile-friendly\n"
            "- Plain text: fallback version\n"
            "- CTA: clear action button text"
        )
        data = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")

        campaign = MarketingCampaign(
            business_id=business_id,
            project_id=project_id,
            product_id=product_id,
            campaign_type="email",
            name=campaign_name,
            goal=goal,
            status="pending_approval",  # ALWAYS requires approval
            lifecycle_status="pending_approval",
            content=data,
            targeting={"recipient_count": recipient_count, "goal": goal},
            metrics={
                "sent": 0,
                "opens": 0,
                "clicks": 0,
                "conversions": 0,
                "revenue_cents": 0,
                "analytics_source": "real",
            },
            analytics_source="real",
        )
        self.db.add(campaign)
        await self.db.commit()
        await self.db.refresh(campaign)
        logger.info(
            "Email campaign generated  business_id=%s  name=%r  status=pending_approval",
            business_id, campaign_name,
        )
        return campaign

    # ── Social Content ────────────────────────────────────────────────────────

    async def generate_social_content(
        self,
        business_id: UUID,
        platform: str,
        business_context: dict,
        product_context: dict | None = None,
        project_id: UUID | None = None,
        product_id: UUID | None = None,
        post_count: int = 5,
    ) -> MarketingCampaign:
        """Generate social media posts. Returns draft for review."""
        platform_instructions = {
            "twitter": f"Write {post_count} Twitter/X posts, max 280 chars each. Include relevant hashtags.",
            "linkedin": f"Write {post_count} LinkedIn posts, professional tone, 150-300 chars each.",
            "instagram": f"Write {post_count} Instagram captions with emojis and hashtags, 100-200 chars each.",
        }
        instruction = platform_instructions.get(platform.lower(), f"Write {post_count} social media posts.")
        product_block = ""
        if product_context:
            product_block = (
                f"Featured product: {product_context.get('name')}\n"
                f"Product description: {product_context.get('description')}\n"
                f"Product price: {product_context.get('price')} {product_context.get('currency', 'USD')}\n"
                f"Product type: {product_context.get('product_type', 'digital')}\n"
            )

        prompt = (
            f"You are a social media expert for {platform}.\n"
            f"{instruction}\n"
            "Return ONLY valid JSON with key 'posts' as an array of objects.\n"
            "Each object: {text, hashtags (array), best_time_to_post}\n\n"
            f"Business: {business_context.get('name')}\n"
            f"Niche: {business_context.get('niche')}\n"
            f"Brand tone: {business_context.get('brand_tone', 'engaging')}\n"
            f"Target audience: {business_context.get('target_audience')}\n"
            f"{product_block}"
            f"{REPORT_INTELLIGENCE_CONTEXT}\n"
        )
        data = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")

        campaign = MarketingCampaign(
            business_id=business_id,
            project_id=project_id,
            product_id=product_id,
            campaign_type="social",
            name=f"{platform.title()} Content Pack",
            status="draft",
            lifecycle_status="draft",
            content={"platform": platform, **data},
            targeting={"platform": platform},
            metrics={
                "clicks": 0,
                "conversions": 0,
                "revenue_cents": 0,
                "analytics_source": "real",
            },
            analytics_source="real",
        )
        self.db.add(campaign)
        await self.db.commit()
        await self.db.refresh(campaign)
        return campaign

    # ── Ad Campaigns ──────────────────────────────────────────────────────────

    async def generate_ad_campaign(
        self,
        business_id: UUID,
        platform: str,
        budget_usd: float,
        business_context: dict,
        products: list[dict],
        selected_product: dict | None = None,
        project_id: UUID | None = None,
        product_id: UUID | None = None,
    ) -> MarketingCampaign:
        """Generate ad campaign payload. ALWAYS requires approval. Never auto-spends."""
        featured_product_block = ""
        if selected_product:
            featured_product_block = (
                f"Featured product: {selected_product.get('name')}\n"
                f"Featured description: {selected_product.get('description')}\n"
                f"Featured price: {selected_product.get('price')} {selected_product.get('currency', 'USD')}\n"
                f"Featured product type: {selected_product.get('product_type', 'digital')}\n"
            )
        prompt = (
            f"You are a {platform} ads expert.\n"
            "Generate a complete ad campaign payload.\n"
            "Return ONLY valid JSON with these keys:\n"
            "  campaign_name, objective, target_audience (object), "
            "  ad_sets (array), ad_creatives (array with headline/description/cta), "
            "  estimated_reach, estimated_cpc_usd, recommended_daily_budget_usd\n\n"
            f"Business: {business_context.get('name')}\n"
            f"Niche: {business_context.get('niche')}\n"
            f"Target audience: {business_context.get('target_audience')}\n"
            f"Products: {[p.get('name') for p in products[:3]]}\n"
            f"{featured_product_block}"
            f"Total budget: ${budget_usd}\n"
            f"Platform: {platform}\n\n"
            f"{REPORT_INTELLIGENCE_CONTEXT}\n"
            "IMPORTANT: This is a PAYLOAD ONLY. No actual spending will occur.\n"
            "The user must approve before any campaign is launched."
        )
        data = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")

        campaign = MarketingCampaign(
            business_id=business_id,
            project_id=project_id,
            product_id=product_id,
            campaign_type=f"{platform.lower()}_ads",
            name=data.get("campaign_name", f"{platform} Campaign"),
            goal=data.get("objective"),
            budget_cents=int(budget_usd * 100),
            status="pending_approval",  # ALWAYS — never auto-launch ads
            content=data,
            targeting={
                "platform": platform,
                "budget_usd": budget_usd,
                "requires_human_approval": True,
            },
            lifecycle_status="pending_approval",
            metrics={
                "clicks": 0,
                "conversions": 0,
                "revenue_cents": 0,
                "analytics_source": "real",
            },
            analytics_source="real",
        )
        self.db.add(campaign)
        await self.db.commit()
        await self.db.refresh(campaign)
        logger.info(
            "Ad campaign generated  business_id=%s  platform=%s  status=pending_approval",
            business_id, platform,
        )
        return campaign

    # ── Campaign Management ───────────────────────────────────────────────────

    async def list_campaigns(
        self, business_id: UUID, campaign_type: str | None = None, limit: int = 50, offset: int = 0
    ) -> list[MarketingCampaign]:
        query = (
            select(MarketingCampaign)
            .where(
                MarketingCampaign.business_id == business_id,
                MarketingCampaign.parent_campaign_id.is_(None),
            )
            .order_by(MarketingCampaign.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        if campaign_type:
            query = query.where(MarketingCampaign.campaign_type == campaign_type)
        result = await self.db.execute(query)
        campaigns = list(result.scalars().all())
        for campaign in campaigns:
            campaign.metrics = await self.real_campaign_metrics(campaign.id)
        return campaigns

    async def real_campaign_metrics(self, campaign_id: UUID) -> dict:
        result = await self.db.execute(
            select(
                AnalyticsEvent.event_type,
                func.count(AnalyticsEvent.id),
                func.coalesce(func.sum(AnalyticsEvent.value_cents), 0),
            )
            .where(AnalyticsEvent.campaign_id == campaign_id)
            .group_by(AnalyticsEvent.event_type)
        )
        clicks = conversions = opens = sent = 0
        revenue_cents = 0
        for event_type, count, value in result.all():
            if event_type == "click":
                clicks = count or 0
            elif event_type == "conversion":
                conversions = count or 0
                revenue_cents += int(value or 0)
            elif event_type == "email_open":
                opens = count or 0
            elif event_type in {"email_sent", "sent"}:
                sent = count or 0
        return {
            "impressions": 0,
            "clicks": clicks,
            "conversions": conversions,
            "opens": opens,
            "sent": sent,
            "revenue_cents": revenue_cents,
            "ctr": 0,
            "roas": 0,
            "analytics_source": "real",
        }

    async def approve_campaign(
        self, campaign_id: UUID, approved_by: str
    ) -> MarketingCampaign | None:
        """Approve a draft or pending campaign. Sending/publishing remains explicit."""
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign:
            return None
        current_status = str(campaign.status or "").lower()
        lifecycle_status = str(campaign.lifecycle_status or "").lower()
        approvable = {"draft", "pending_approval", "pending approval", "rejected", "approved"}
        if current_status not in approvable and lifecycle_status not in approvable:
            return None
        campaign.status = "approved"
        campaign.lifecycle_status = "approved"
        campaign.approved_by = approved_by
        await self.db.commit()
        logger.info("Campaign approved  id=%s  by=%s", campaign_id, approved_by)
        return campaign

    async def reject_campaign(
        self, campaign_id: UUID, reason: str
    ) -> MarketingCampaign | None:
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign:
            return None
        campaign.status = "rejected"
        campaign.rejection_reason = reason
        await self.db.commit()
        return campaign

    async def update_campaign_content(
        self,
        campaign_id: UUID,
        *,
        name: str | None = None,
        content: dict | None = None,
        content_text: str | None = None,
    ) -> MarketingCampaign | None:
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign:
            return None
        if name is not None and name.strip():
            campaign.name = name.strip()[:200]
        if content is not None:
            campaign.content = content
        elif content_text is not None:
            campaign.content = self._with_primary_text(campaign.content or {}, content_text)
        await self.db.commit()
        await self.db.refresh(campaign)
        return campaign

    @staticmethod
    def _with_primary_text(content: dict, text: str) -> dict:
        next_content = dict(content or {})
        if isinstance(next_content.get("posts"), list) and next_content["posts"]:
            first = dict(next_content["posts"][0] or {})
            first["text"] = text
            next_content["posts"] = [first, *next_content["posts"][1:]]
        elif "plain_text_body" in next_content or "html_body" in next_content:
            next_content["plain_text_body"] = text
            next_content["body"] = text
        elif "content_markdown" in next_content:
            next_content["content_markdown"] = text
        elif "post_text" in next_content:
            next_content["post_text"] = text
        elif "body" in next_content:
            next_content["body"] = text
        elif "headline" in next_content:
            next_content["headline"] = text
        else:
            next_content["body"] = text
        return next_content

    async def duplicate_campaign(self, campaign_id: UUID) -> MarketingCampaign | None:
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign:
            return None
        new_campaign = MarketingCampaign(
            business_id=campaign.business_id,
            campaign_type=campaign.campaign_type,
            name=f"Copy of {campaign.name}",
            goal=campaign.goal,
            budget_cents=campaign.budget_cents,
            status="draft",
            lifecycle_status="draft",
            content=campaign.content,
            targeting=campaign.targeting,
            metrics={"impressions": 0, "clicks": 0, "conversions": 0, "revenue_cents": 0, "analytics_source": "real"},
            analytics_source="real",
        )
        self.db.add(new_campaign)
        await self.db.commit()
        await self.db.refresh(new_campaign)
        return new_campaign

    async def send_approved_email_campaign(
        self,
        campaign_id: UUID,
        recipient_emails: list[str],
        user_id: str,
    ) -> dict:
        """Send an approved email campaign to a list of recipients."""
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign:
            return {"error": "Campaign not found"}
        if campaign.status != "approved":
            return {"error": f"Campaign is not approved (status: {campaign.status})"}
        if campaign.campaign_type != "email":
            return {"error": "Only email campaigns can be sent via this method"}

        from app.services.email_service import EmailService
        svc = EmailService()
        content = campaign.content
        sent = 0
        failed = 0

        from datetime import datetime, timezone

        for email in recipient_emails:
            contact = await self._get_or_create_contact(campaign.business_id, email)
            recipient = CampaignRecipient(
                campaign_id=campaign.id,
                contact_id=contact.id if contact else None,
                email=email.strip().lower(),
                status="sending",
            )
            self.db.add(recipient)
            await self.db.flush()
            success = await svc.send_marketing_campaign(
                user_id=user_id,
                to=email,
                subject=content.get("subject", "Message from us"),
                html_body=content.get("html_body", ""),
                db=self.db,
            )
            if success:
                sent += 1
                recipient.status = "sent"
                recipient.sent_at = datetime.now(timezone.utc)
                self.db.add(
                    AnalyticsEvent(
                        business_id=campaign.business_id,
                        product_id=campaign.product_id,
                        campaign_id=campaign.id,
                        contact_id=recipient.contact_id,
                        event_type="email_sent",
                        source="email_provider",
                        value_cents=0,
                        metadata_json={"recipient_id": str(recipient.id), "email": recipient.email},
                    )
                )
            else:
                failed += 1
                recipient.status = "failed"

        if sent > 0:
            campaign.status = "sent"
            campaign.lifecycle_status = "sent"
        else:
            campaign.status = "approved"
            campaign.lifecycle_status = "approved"
        campaign.metrics = {
            "sent": sent,
            "failed": failed,
            "total": len(recipient_emails),
            "clicks": 0,
            "conversions": 0,
            "revenue_cents": 0,
            "analytics_source": "real",
        }
        await self.db.commit()
        logger.info("Email campaign sent  id=%s  sent=%d  failed=%d", campaign_id, sent, failed)
        if sent == 0:
            return {
                "error": (
                    "Email provider did not send any recipients. Configure a verified sender/API key "
                    "or connect Gmail before retrying."
                ),
                "sent": sent,
                "failed": failed,
            }
        return {"sent": sent, "failed": failed}

    async def _get_or_create_contact(self, business_id: UUID, email: str) -> Contact | None:
        normalized = email.strip().lower()
        if not normalized:
            return None
        result = await self.db.execute(
            select(Contact).where(Contact.business_id == business_id, Contact.email == normalized)
        )
        contact = result.scalar_one_or_none()
        if contact:
            return contact
        contact = Contact(
            business_id=business_id,
            email=normalized,
            source="email_campaign",
            consent_status="unknown",
        )
        self.db.add(contact)
        await self.db.flush()
        return contact

    async def generate_ab_test_variant(self, campaign_id: UUID) -> MarketingCampaign | None:
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign:
            return None
        
        prompt = (
            f"You are an expert copywriter. I have a marketing campaign named '{campaign.name}'.\n"
            f"Here is the original content: {json.dumps(campaign.content)}\n\n"
            f"{REPORT_INTELLIGENCE_CONTEXT}\n"
            "Generate a 'Variant B' for an A/B test. It should use a completely different angle, "
            "tone, or hook, but achieve the same goal. Return ONLY valid JSON that matches the "
            "original schema structure exactly."
        )
        variant_b = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")
        
        campaign.variant_b_content = json.dumps(variant_b)
        campaign.ab_test_active = True
        await self.db.commit()
        await self.db.refresh(campaign)
        return campaign

    async def generate_custom_content(
        self,
        business_id: UUID,
        content_type: str,
        tone: str,
        audience: str,
        cta: str,
        business_context: dict,
        goal: str = "",
        product_context: dict | None = None,
        project_id: UUID | None = None,
        product_id: UUID | None = None,
    ) -> MarketingCampaign:
        content_specs = {
            "linkedin_post": {
                "campaign_type": "social",
                "name": "LinkedIn Content",
                "schema": "posts: array of objects with text, hashtags, best_time_to_post",
                "platform": "linkedin",
                "instructions": "Write a polished LinkedIn post with a strong hook, business insight, and clear CTA.",
            },
            "twitter_thread": {
                "campaign_type": "social",
                "name": "Twitter Thread",
                "schema": "posts: array of objects with text, hashtags, best_time_to_post",
                "platform": "twitter",
                "instructions": "Write a concise Twitter/X thread. Each post must fit within 280 characters.",
            },
            "instagram_caption": {
                "campaign_type": "social",
                "name": "Instagram Caption",
                "schema": "posts: array of objects with text, hashtags, best_time_to_post",
                "platform": "instagram",
                "instructions": "Write an Instagram caption with a sharp opening line, useful body, and hashtags.",
            },
            "youtube_description": {
                "campaign_type": "social",
                "name": "YouTube Description",
                "schema": "headline, body, hashtags, cta_text",
                "platform": "youtube",
                "instructions": "Write a YouTube video description with title-style headline, search-friendly body, chapters suggestion, and CTA.",
            },
            "email_sequence": {
                "campaign_type": "email",
                "name": "Email Sequence",
                "schema": "subject, preview_text, html_body, plain_text_body, cta_text, sequence_steps",
                "platform": "email",
                "instructions": "Write a conversion-focused email sequence with subject, preview text, HTML body, plain text body, CTA, and sequence steps.",
            },
            "blog_post": {
                "campaign_type": "seo_blog",
                "name": "SEO Blog Post",
                "schema": "title, slug, meta_description, content_markdown, keywords",
                "platform": "wordpress",
                "instructions": "Write a practical SEO blog post in markdown with H2/H3 headings and a keyword-aware meta description.",
            },
            "ad_copy": {
                "campaign_type": "google_ads",
                "name": "Ad Copy",
                "schema": "campaign_name, objective, headlines, descriptions, ad_creatives, target_audience, recommended_daily_budget_usd",
                "platform": "google_ads",
                "instructions": "Write Google Ads copy with multiple headlines, descriptions, target audience, and recommended budget.",
            },
        }
        spec = content_specs.get(content_type, content_specs["linkedin_post"])
        product_block = ""
        if product_context:
            product_block = (
                f"Featured product: {product_context.get('name')}\n"
                f"Product description: {product_context.get('description')}\n"
                f"Product price: {product_context.get('price')} {product_context.get('currency', 'USD')}\n"
                f"Product type: {product_context.get('product_type', 'digital')}\n"
            )

        prompt = (
            "You are the Marketing Engine inside an AI business operating system.\n"
            f"{spec['instructions']}\n"
            f"Return ONLY valid JSON with this schema: {spec['schema']}.\n\n"
            f"Business: {business_context.get('name')}\n"
            f"Niche: {business_context.get('niche')}\n\n"
            f"Business description: {business_context.get('description', '')}\n"
            f"Brand tone: {business_context.get('brand_tone') or tone}\n"
            f"Default target audience: {business_context.get('target_audience')}\n"
            f"Recent agent research: {business_context.get('recent_agent_research') or 'No recent agent research.'}\n"
            f"Requested target audience: {audience}\n"
            f"Campaign goal/topic: {goal or 'Create useful launch-ready content'}\n"
            f"Call to action: {cta}\n"
            f"{product_block}\n"
            f"{REPORT_INTELLIGENCE_CONTEXT}\n"
            "Make the output immediately usable by a human marketer. Do not include placeholder text."
        )
        data = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")

        if "posts" in data and isinstance(data["posts"], list) and spec["platform"] not in {"email", "wordpress"}:
            data = {"platform": spec["platform"], **data}
        elif spec["platform"] not in data:
            data = {"platform": spec["platform"], **data}

        status = "pending_approval" if spec["campaign_type"] in {"email", "google_ads", "meta_ads"} else "draft"
        campaign = MarketingCampaign(
            business_id=business_id,
            project_id=project_id,
            product_id=product_id,
            campaign_type=spec["campaign_type"],
            name=f"{spec['name']} - {goal[:60] if goal else tone}",
            status=status,
            content=data,
            targeting={
                "audience": audience,
                "tone": tone,
                "cta": cta,
                "goal": goal,
                "content_type": content_type,
                "platform": spec["platform"],
            },
            lifecycle_status="pending_approval",
            metrics={
                "clicks": 0,
                "conversions": 0,
                "revenue_cents": 0,
                "analytics_source": "real",
            },
            analytics_source="real",
        )
        self.db.add(campaign)
        await self.db.commit()
        await self.db.refresh(campaign)
        return campaign

