"""Marketing Engine — real AI-generated campaigns, SEO content, and ad payloads.

All content is generated by the real AI provider (Ollama/Groq/HF).
No dummy data. If AI is unavailable, raises AIProviderError.

Approval workflow:
- Email campaigns → status="pending_approval" until user approves
- Ad campaigns → status="pending_approval" always (never auto-launch)
- SEO blogs → status="draft", user publishes manually

Uses SmartAIOrchestrator for intelligent provider selection and retry strategy.
"""
from __future__ import annotations

import logging
import re
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.marketing import MarketingCampaign, SeoContent
from app.services.ai_orchestrator import generate_json_smart, generate_text_smart, ProviderChoice

logger = logging.getLogger(__name__)


class MarketingService:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db

    # ── SEO Content ───────────────────────────────────────────────────────────

    async def generate_seo_blog(
        self,
        business_id: UUID,
        topic: str,
        target_keyword: str,
        business_context: dict,
    ) -> SeoContent:
        """Generate a full SEO blog post using real AI with smart provider selection."""
        prompt = (
            "You are an expert SEO content writer.\n"
            "Write a complete, high-quality SEO blog post.\n"
            "Return ONLY valid JSON with these keys:\n"
            "  title, slug, meta_description, content_markdown, keywords (array of strings)\n\n"
            f"Business: {business_context.get('name')}\n"
            f"Niche: {business_context.get('niche')}\n"
            f"Target audience: {business_context.get('target_audience')}\n"
            f"Topic: {topic}\n"
            f"Primary keyword: {target_keyword}\n\n"
            "Requirements:\n"
            "- Title: compelling, includes keyword, under 60 chars\n"
            "- Slug: URL-friendly, lowercase, hyphens\n"
            "- Meta description: 150-160 chars, includes keyword\n"
            "- Content: 800-1200 words, markdown format, H2/H3 headings, practical value\n"
            "- Keywords: 5-8 related keywords"
        )
        # Use smart orchestrator for intelligent provider selection
        data = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")
        content_md = data.get("content_markdown", "")
        word_count = len(content_md.split())

        seo = SeoContent(
            business_id=business_id,
            title=data.get("title", topic),
            slug=data.get("slug", re.sub(r"[^a-z0-9]+", "-", topic.lower())),
            meta_description=data.get("meta_description", ""),
            content_markdown=content_md,
            keywords=data.get("keywords", [target_keyword]),
            status="draft",
            word_count=word_count,
        )
        self.db.add(seo)
        await self.db.commit()
        await self.db.refresh(seo)
        logger.info("SEO blog generated  business_id=%s  title=%r", business_id, seo.title)
        return seo

    async def list_seo_content(self, business_id: UUID) -> list[SeoContent]:
        result = await self.db.execute(
            select(SeoContent)
            .where(SeoContent.business_id == business_id)
            .order_by(SeoContent.created_at.desc())
        )
        return list(result.scalars().all())

    async def publish_seo_content(self, content_id: UUID) -> SeoContent | None:
        content = await self.db.get(SeoContent, content_id)
        if not content:
            return None
        content.status = "published"
        await self.db.commit()
        return content

    # ── Email Campaigns ───────────────────────────────────────────────────────

    async def generate_email_campaign(
        self,
        business_id: UUID,
        campaign_name: str,
        goal: str,
        business_context: dict,
        product_context: dict | None = None,
        project_id: UUID | None = None,
        product_id: UUID | None = None,
        recipient_count: int = 0,
    ) -> MarketingCampaign:
        """Generate an email campaign. Requires human approval before sending."""
        product_block = ""
        if product_context:
            product_block = (
                f"Featured product: {product_context.get('name')}\n"
                f"Product description: {product_context.get('description')}\n"
                f"Product price: {product_context.get('price')} {product_context.get('currency', 'USD')}\n"
                f"Product type: {product_context.get('product_type', 'digital')}\n"
            )
        prompt = (
            "You are an expert email marketer.\n"
            "Generate a high-converting email campaign.\n"
            "Return ONLY valid JSON with these keys:\n"
            "  subject, preview_text, html_body, plain_text_body, cta_text, cta_url_placeholder\n\n"
            f"Business: {business_context.get('name')}\n"
            f"Niche: {business_context.get('niche')}\n"
            f"Brand tone: {business_context.get('brand_tone', 'professional')}\n"
            f"Target audience: {business_context.get('target_audience')}\n"
            f"{product_block}"
            f"Campaign goal: {goal}\n\n"
            "Requirements:\n"
            "- Subject: compelling, under 50 chars, no spam words\n"
            "- Preview text: 90-100 chars\n"
            "- HTML body: clean HTML email, mobile-friendly\n"
            "- Plain text: fallback version\n"
            "- CTA: clear action button text"
        )
        data = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")

        campaign = MarketingCampaign(
            business_id=business_id,
            project_id=project_id,
            product_id=product_id,
            campaign_type="email",
            name=campaign_name,
            status="pending_approval",  # ALWAYS requires approval
            content=data,
            targeting={"recipient_count": recipient_count, "goal": goal},
            metrics={},
        )
        self.db.add(campaign)
        await self.db.commit()
        await self.db.refresh(campaign)
        logger.info(
            "Email campaign generated  business_id=%s  name=%r  status=pending_approval",
            business_id, campaign_name,
        )
        return campaign

    # ── Social Content ────────────────────────────────────────────────────────

    async def generate_social_content(
        self,
        business_id: UUID,
        platform: str,
        business_context: dict,
        product_context: dict | None = None,
        project_id: UUID | None = None,
        product_id: UUID | None = None,
        post_count: int = 5,
    ) -> MarketingCampaign:
        """Generate social media posts. Returns draft for review."""
        platform_instructions = {
            "twitter": f"Write {post_count} Twitter/X posts, max 280 chars each. Include relevant hashtags.",
            "linkedin": f"Write {post_count} LinkedIn posts, professional tone, 150-300 chars each.",
            "instagram": f"Write {post_count} Instagram captions with emojis and hashtags, 100-200 chars each.",
        }
        instruction = platform_instructions.get(platform.lower(), f"Write {post_count} social media posts.")
        product_block = ""
        if product_context:
            product_block = (
                f"Featured product: {product_context.get('name')}\n"
                f"Product description: {product_context.get('description')}\n"
                f"Product price: {product_context.get('price')} {product_context.get('currency', 'USD')}\n"
                f"Product type: {product_context.get('product_type', 'digital')}\n"
            )

        prompt = (
            f"You are a social media expert for {platform}.\n"
            f"{instruction}\n"
            "Return ONLY valid JSON with key 'posts' as an array of objects.\n"
            "Each object: {text, hashtags (array), best_time_to_post}\n\n"
            f"Business: {business_context.get('name')}\n"
            f"Niche: {business_context.get('niche')}\n"
            f"Brand tone: {business_context.get('brand_tone', 'engaging')}\n"
            f"Target audience: {business_context.get('target_audience')}\n"
            f"{product_block}"
        )
        data = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")

        campaign = MarketingCampaign(
            business_id=business_id,
            project_id=project_id,
            product_id=product_id,
            campaign_type="social",
            name=f"{platform.title()} Content Pack",
            status="draft",
            content={"platform": platform, **data},
            targeting={"platform": platform},
            metrics={},
        )
        self.db.add(campaign)
        await self.db.commit()
        await self.db.refresh(campaign)
        return campaign

    # ── Ad Campaigns ──────────────────────────────────────────────────────────

    async def generate_ad_campaign(
        self,
        business_id: UUID,
        platform: str,
        budget_usd: float,
        business_context: dict,
        products: list[dict],
        selected_product: dict | None = None,
        project_id: UUID | None = None,
        product_id: UUID | None = None,
    ) -> MarketingCampaign:
        """Generate ad campaign payload. ALWAYS requires approval. Never auto-spends."""
        featured_product_block = ""
        if selected_product:
            featured_product_block = (
                f"Featured product: {selected_product.get('name')}\n"
                f"Featured description: {selected_product.get('description')}\n"
                f"Featured price: {selected_product.get('price')} {selected_product.get('currency', 'USD')}\n"
                f"Featured product type: {selected_product.get('product_type', 'digital')}\n"
            )
        prompt = (
            f"You are a {platform} ads expert.\n"
            "Generate a complete ad campaign payload.\n"
            "Return ONLY valid JSON with these keys:\n"
            "  campaign_name, objective, target_audience (object), "
            "  ad_sets (array), ad_creatives (array with headline/description/cta), "
            "  estimated_reach, estimated_cpc_usd, recommended_daily_budget_usd\n\n"
            f"Business: {business_context.get('name')}\n"
            f"Niche: {business_context.get('niche')}\n"
            f"Target audience: {business_context.get('target_audience')}\n"
            f"Products: {[p.get('name') for p in products[:3]]}\n"
            f"{featured_product_block}"
            f"Total budget: ${budget_usd}\n"
            f"Platform: {platform}\n\n"
            "IMPORTANT: This is a PAYLOAD ONLY. No actual spending will occur.\n"
            "The user must approve before any campaign is launched."
        )
        data = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")

        campaign = MarketingCampaign(
            business_id=business_id,
            project_id=project_id,
            product_id=product_id,
            campaign_type=f"{platform.lower()}_ads",
            name=data.get("campaign_name", f"{platform} Campaign"),
            status="pending_approval",  # ALWAYS — never auto-launch ads
            content=data,
            targeting={
                "platform": platform,
                "budget_usd": budget_usd,
                "requires_human_approval": True,
            },
            metrics={},
        )
        self.db.add(campaign)
        await self.db.commit()
        await self.db.refresh(campaign)
        logger.info(
            "Ad campaign generated  business_id=%s  platform=%s  status=pending_approval",
            business_id, platform,
        )
        return campaign

    # ── Campaign Management ───────────────────────────────────────────────────

    async def list_campaigns(
        self, business_id: UUID, campaign_type: str | None = None, limit: int = 50, offset: int = 0
    ) -> list[MarketingCampaign]:
        query = (
            select(MarketingCampaign)
            .where(MarketingCampaign.business_id == business_id)
            .order_by(MarketingCampaign.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        if campaign_type:
            query = query.where(MarketingCampaign.campaign_type == campaign_type)
        result = await self.db.execute(query)
        return list(result.scalars().all())

    async def approve_campaign(
        self, campaign_id: UUID, approved_by: str
    ) -> MarketingCampaign | None:
        """Approve a pending campaign. For email: triggers send. For ads: marks ready."""
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign or campaign.status != "pending_approval":
            return None
        campaign.status = "approved"
        campaign.approved_by = approved_by
        await self.db.commit()
        logger.info("Campaign approved  id=%s  by=%s", campaign_id, approved_by)
        return campaign

    async def reject_campaign(
        self, campaign_id: UUID, reason: str
    ) -> MarketingCampaign | None:
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign:
            return None
        campaign.status = "rejected"
        campaign.rejection_reason = reason
        await self.db.commit()
        return campaign

    async def duplicate_campaign(self, campaign_id: UUID) -> MarketingCampaign | None:
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign:
            return None
        new_campaign = MarketingCampaign(
            business_id=campaign.business_id,
            campaign_type=campaign.campaign_type,
            name=f"Copy of {campaign.name}",
            status="draft",
            content=campaign.content,
            targeting=campaign.targeting,
            metrics={"impressions": 0, "clicks": 0, "conversions": 0, "spend_cents": 0},
        )
        self.db.add(new_campaign)
        await self.db.commit()
        await self.db.refresh(new_campaign)
        return new_campaign

    async def send_approved_email_campaign(
        self,
        campaign_id: UUID,
        recipient_emails: list[str],
        user_id: str,
    ) -> dict:
        """Send an approved email campaign to a list of recipients."""
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign:
            return {"error": "Campaign not found"}
        if campaign.status != "approved":
            return {"error": f"Campaign is not approved (status: {campaign.status})"}
        if campaign.campaign_type != "email":
            return {"error": "Only email campaigns can be sent via this method"}

        from app.services.email_service import EmailService
        svc = EmailService()
        content = campaign.content
        sent = 0
        failed = 0

        for email in recipient_emails:
            success = await svc.send_marketing_campaign(
                user_id=user_id,
                to=email,
                subject=content.get("subject", "Message from us"),
                html_body=content.get("html_body", ""),
                db=self.db,
            )
            if success:
                sent += 1
            else:
                failed += 1

        campaign.status = "sent"
        campaign.metrics = {"sent": sent, "failed": failed, "total": len(recipient_emails)}
        await self.db.commit()
        logger.info("Email campaign sent  id=%s  sent=%d  failed=%d", campaign_id, sent, failed)
        return {"sent": sent, "failed": failed}

    async def generate_ab_test_variant(self, campaign_id: UUID) -> MarketingCampaign | None:
        campaign = await self.db.get(MarketingCampaign, campaign_id)
        if not campaign:
            return None
        
        prompt = (
            f"You are an expert copywriter. I have a marketing campaign named '{campaign.name}'.\n"
            f"Here is the original content: {json.dumps(campaign.content)}\n\n"
            "Generate a 'Variant B' for an A/B test. It should use a completely different angle, "
            "tone, or hook, but achieve the same goal. Return ONLY valid JSON that matches the "
            "original schema structure exactly."
        )
        import json
        variant_b = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")
        
        campaign.variant_b_content = json.dumps(variant_b)
        campaign.ab_test_active = True
        await self.db.commit()
        await self.db.refresh(campaign)
        return campaign

    async def generate_custom_content(
        self, business_id: UUID, content_type: str, tone: str, audience: str, cta: str, business_context: dict
    ) -> MarketingCampaign:
        prompt = (
            f"You are a master social media manager and content creator.\n"
            f"Generate a {content_type} for the business below.\n"
            f"Tone: {tone}\nTarget Audience: {audience}\nCall to Action: {cta}\n\n"
            f"Business: {business_context.get('name')}\n"
            f"Niche: {business_context.get('niche')}\n\n"
            "Return ONLY valid JSON containing a single key 'posts' which is an array of objects. "
            "Each object should have a 'text' key with the actual content."
        )
        data = await generate_json_smart(prompt, prefer_provider=ProviderChoice.AUTO, task_type="marketing")

        campaign = MarketingCampaign(
            business_id=business_id,
            campaign_type="custom_social",
            name=f"Custom {content_type} - {tone.capitalize()}",
            status="draft",
            content=data,
            targeting={"audience": audience, "tone": tone, "cta": cta},
            metrics={},
        )
        self.db.add(campaign)
        await self.db.commit()
        await self.db.refresh(campaign)
        return campaign

